### PR TITLE
Read and write bitpacked input

### PR DESCRIPTION
**Pull request by AdamHillier**
Opening this just to run CI.

### CODE REVIEW

**Comment by AdamHillier** [comment]
@lgeiger I don't suppose you have any insight here?

The file `optimize_patterns.td` causes a segfault during code generation that I've spent all weekend trying to debug.

```
ERROR: /Users/adamwork/src/compute-engine/larq_compute_engine/mlir/BUILD:39:1: Generating code from table: transforms/optimize_patterns.td //larq_compute_engine/mlir:optimize_lce_inc_gen__gen_rewriters_genrule failed (Segmentation fault): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
```

I cannot understand what the problem is. I *have* been able to get this to work a few times by repeatedly running the `bazel test ...` command again and again after the error comes up - sometimes it eventually behaves and compiles the rewrite patterns, at which point the tests pass. But it never works in one go consistently.

Under these two scenarios, it does compile:

- In this PR I've added two boolean flags to the op definition, and bizarrely the rewrite pattern compiles just fine if I comment out one of those flags (at every mention). It's fine with one, but refuses to compile with two boolean flags.

- Compiling also works if I comment out the second of the two patterns in `FuseActFnIntoConvOpPat`, at which point the optimize mlir test of course doesn't pass.

The fact that it sometimes works fine makes no sense to me, and suggests a bug in the TableGen compiler.

I am at my wit's end, and perilously close to rewriting all of the remaining optimize rules in C++ so as to not have to touch this horrible thing (TableGen) ever again.

**Comment by lgeiger** [comment]
> @lgeiger I don't suppose you have any insight here?

Unfortunately not. We can take a closer look at it tomorrow.

You could check if this issue still exists when building on top of https://github.com/larq/compute-engine/pull/258 which includes a newer version of MLIR. There've been a lot of changes between the MLIR versions used in TF 2.1 and TF 2.2, so it might be worth a shot if you suspect a TableGen bug.

> The fact that it sometimes works fine makes no sense to me, and suggests a bug in the TableGen compiler.

That might be the case, if we can't figure out the cause of this we could ask for help on the [MLIR forum](https://llvm.discourse.group/c/llvm-project/mlir) or the [MLIR chat](https://discordapp.com/invite/xS7Z362).

> I am at my wit's end, and perilously close to rewriting all of the remaining optimize rules in C++ so as to not have to touch this horrible thing (TableGen) ever again.

I can relate to the frustration with TableGen, but I would be strongly against rewriting everything in C++ since it would make it a lot harder to add simple transformations.

**Comment by AdamHillier** [comment]
> I can relate to the frustration with TableGen, but I would be strongly against rewriting everything in C++ since it would make it a lot harder to add simple transformations.

Ah I know, not really a serious suggestion. I just wish the TableGen stuff was more intuitive....

> You could check if this issue still exists when building on top of [larq#258](https://github.com/larq/compute-engine/pull/258) which includes a newer version of MLIR. There've been a lot of changes between the MLIR versions used in TF 2.1 and TF 2.2, so it might be worth a shot if you suspect a TableGen bug.

Indeed this does work (at least locally), thank you very much for suggesting it :+1:.

**Comment by lgeiger** [comment]
> Indeed this does work (at least locally), thank you very much for suggesting it 👍.

That's good news. The compile errors in https://github.com/larq/compute-engine/pull/258 for the kernels should be a lot easier to fix compared to debugging the TableGen segfaults.

**Pull request closed without merging**
